name: CI Процесс

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkstyle
        run: mvn checkstyle:check

      - name: Run tests and check coverage
        run: mvn test jacoco:check

      - name: Generate JaCoCo report
        run: mvn jacoco:report
